Bump pkl.impl.ghactions to version 1.8.1

diff --git a/.github/workflows/prb.yml b/.github/workflows/prb.yml
--- a/.github/workflows/prb.yml
+++ b/.github/workflows/prb.yml
@@ -141,7 +141,7 @@ jobs:
         ./scripts/create_notice.sh
         git diff --exit-code
   verdict:
-    if: '!cancelled() && !failure()'
+    if: always()
     needs:
     - check-pkl-github-actions
     - test-pkl-0-25-3
@@ -151,7 +151,11 @@ jobs:
     - check-format-go
     runs-on: ubuntu-latest
     steps:
-    - run: 'true'
+    - name: Failure verdict
+      if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')
+      run: |-
+        echo "Some of the required jobs are either failing or were cancelled"
+        exit 1
   upload-event-file:
     runs-on: ubuntu-latest
     steps:
